touchdown_velocity: 0.4
touchdown_z_thresh: 0.3
lost_target_alt: 8
max_acc_xy: 1
max_devel_xy: 1
max_speed_xy: 1
max_vel_z: 1
decay_start_z: 3
limit_start_z: 3
gamma_yaw: 1
max_gamma_xy: 0.25
min_gamma_xy: 0.1
max_gamma_z: 0.5
vision_kp: 1
xy_align_thresh: 0.45
yaw_align_thresh: 0.2
blind_drop_xy_thresh: 0.2
blind_drop_alt: 0.3
exit_alt: 0.1
max_hold_dist_thresh: 1.8
min_hold_dist_thresh: 0.2
min_hold_dist_thresh_alt: 0.5
max_funnel_radius: 0.15
funnel_radius_k: 0.1
max_ff_vel: 1.5
lost_climb_vel: 0.4
use_disarm: true
use_ff_vel: true
target_timeout: 1
target_distance: 3
target_distance_hysteresis: 1
